---
- name: Create the node_exporter group
  group:
    name: "{{ node_exporter_group }}"
    state: present
    system: true

- name: Create the node_exporter user
  user:
    name: "{{ node_exporter_user }}"
